<a href="https://colab.research.google.com/github/NehaSrinivas98/MachineLearningCourse/blob/main/pythonAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a program that prints a 5x5 grid of asterisks (*) using nested loops.

In [ ]:
for i in range(5):
    for j in range(5):
        print("*", end=" ")
    print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


2. Write a program that asks the user to input numbers until they input 0. The program should print the sum of all the input numbers.

In [ ]:
total = 0
while True:
    res = int(input("Input a number: "))
    if res == 0:
        break
    total += res

print(total)

Input a number: 10
Input a number: 0
10


3.Write a program that prints all the numbers from 1 to 10 except 5 using a for loop and continue statement.

In [ ]:
for i in range(1,11):
  if i == 5:
    continue
  print(i)

1
2
3
4
6
7
8
9
10


4.  Write a program that asks the user to input a number and prints all the even numbers from 1 to that number using a for loop.

In [ ]:
input_number = int(input("Input a number: "))
for i in range(1,input_number+1):
  if i%2 != 0:
    continue
  print(i)


Input a number: 25
2
4
6
8
10
12
14
16
18
20
22
24


5.Write a program that calculates the factorial of a number input by the user using a while loop.

In [ ]:
number = int(input("Enter a number: "))
factorial = 1
i = 1
while i <= number:
    factorial *= i
    i += 1
print(f"The factorial of {number} is {factorial}.")

Enter a number: 20
The factorial of 20 is 2432902008176640000.


6.Write a program that calculates the sum of the digits of a number input by the user using a while loop.

In [ ]:
number = int(input("Enter a number: "))
sum_of_digits = 0
while number > 0:
    digit = number % 10
    sum_of_digits += digit
    number = number // 10
print(f"The sum of the digits is {sum_of_digits}.")

Enter a number: 3456780
The sum of the digits is 33.


7. Prime number check

In [ ]:
number = int(input("Enter a number: "))
is_prime = True
if number <= 1:
    is_prime = False
else:
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            is_prime = False
            break
if is_prime:
    print(f"{number} is a prime number.")
else:
    print(f"{number} is not a prime number.")

8.Write a program that prints the first n Fibonacci numbers, where n is input by the user.

In [ ]:
n = int(input("Enter the number of Fibonacci numbers to print: "))
a, b = 0, 1
count = 0
while count < n:
    print(a)
    a, b = b, a + b
    count += 1

9.Write a function that rotates a list by n positions. Print the original and rotated lists.

In [ ]:
def rotate_list(lst, n):
    return lst[n:] + lst[:n]

original_list = [1, 2, 3, 4, 5]
rotated_list = rotate_list(original_list, 2)
print(f"Original list: {original_list}")
print(f"Rotated list: {rotated_list}")

Original list: [1, 2, 3, 4, 5]
Rotated list: [3, 4, 5, 1, 2]


10.Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.

In [ ]:
def reverse_list(lst):
    return lst[::-1]

original_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(original_list)
print(f"Original list: {original_list}")
print(f"Reversed list: {reversed_list}")

11.Create two lists of the same length. Use the `zip` function to combine these lists into a list of tuples and print the result.

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = ['a', 'b', 'c', 'd', 'e']
zipped = list(zip(list1, list2))
print(zipped)

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]


12.Write a function that takes a nested list and flattens it into a single list. Print the original and flattened lists.

In [ ]:
def flatten_list(nested_list):
    flat_list = [item for sublist in nested_list for item in sublist]
    return flat_list
nested_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
flattened = flatten_list(nested_list)
print("Original nested list:")
print(nested_list)
print("Flattened list:")
print(flattened)

Original nested list:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Flattened list:
[1, 2, 3, 4, 5, 6, 7, 8, 9]


13.Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose. Print the original and transposed matrices.

In [ ]:
def transpose_matrix(matrix):
    transposed = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
    return transposed

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
transposed = transpose_matrix(matrix)
print("Original matrix:")
for row in matrix:
    print(row)
print("Transposed matrix:")
for row in transposed:
    print(row)

Original matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Transposed matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


14.
Create a list of dictionaries where each dictionary represents a student with keys 'name' and 'score'. Sort the list of dictionaries by the 'score' in descending order and print the sorted list.

In [ ]:
students = [
    {'name': 'Alice', 'score': 88},
    {'name': 'Bob', 'score': 72},
    {'name': 'Charlie', 'score': 95},
    {'name': 'David', 'score': 65},
    {'name': 'Eve', 'score': 78}
]
sorted_students = sorted(students, key=lambda x: x['score'], reverse=True)
print("Sorted students by score in descending order:")
for student in sorted_students:
    print(student)

Sorted students by score in descending order:
{'name': 'Charlie', 'score': 95}
{'name': 'Alice', 'score': 88}
{'name': 'Eve', 'score': 78}
{'name': 'Bob', 'score': 72}
{'name': 'David', 'score': 65}


15.Create a list of random numbers and sort it in ascending and descending order. Remove the duplicates from the list and print the modified list.

In [ ]:
import random

random_numbers = [random.randint(1, 20) for _ in range(15)]
print(f"Original list: {random_numbers}")

sorted_numbers = sorted(random_numbers)
print(f"Sorted in ascending order: {sorted_numbers}")

sorted_numbers_desc = sorted(random_numbers, reverse=True)
print(f"Sorted in descending order: {sorted_numbers_desc}")

unique_numbers = list(set(random_numbers))
print(f"List with duplicates removed: {unique_numbers}")

Original list: [3, 4, 20, 15, 14, 11, 9, 20, 6, 19, 11, 6, 7, 18, 15]
Sorted in ascending order: [3, 4, 6, 6, 7, 9, 11, 11, 14, 15, 15, 18, 19, 20, 20]
Sorted in descending order: [20, 20, 19, 18, 15, 15, 14, 11, 11, 9, 7, 6, 6, 4, 3]
List with duplicates removed: [3, 4, 6, 7, 9, 11, 14, 15, 18, 19, 20]


16.Tuple operations

In [ ]:
tpl = tuple(range(1, 11))
print(tpl)
print('First element',tpl[0])
print('Last element',tpl[-1])
print('middle element',tpl[len(tpl) // 2])
print('First 3 elements',tpl[0:3])
print('Last 3 elements',tpl[-3:])
print('Elements from 2 to 5 position',tpl[2:6])


(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
First element 1
Last element 10
middle element 6
First 3 elements (1, 2, 3)
Last 3 elements (8, 9, 10)
Elements from 2 to 5 position (3, 4, 5, 6)


17.Create a nested tuple representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

In [ ]:
tpl_matrix = ((1,2,3),(4,5,6),(7,8,9))
print('2nd row 3rd column',tpl_matrix[1][2])

2nd row 3rd column 6


18.Concatenate two tuples: (1, 2, 3) and (4, 5, 6). Print the resulting tuple.

In [ ]:
tp1=(1,2,3)
tp2=(4,5,6)
print('Concatenated tuple',tp1+tp2)

Concatenated tuple (1, 2, 3, 4, 5, 6)


19.Create a tuple with duplicate elements and count the occurrences of an element. Find the index of the first occurrence of an element in the tuple.

In [ ]:
tpl = (1, 2, 2, 3, 4, 4, 4, 5)
print(f"Occurrences of 4: {tpl.count(4)}")
print(f"Index of first occurrence of 2: {tpl.index(2)}")

20.Create a tuple with 5 elements and unpack it into 5 variables. Print the variables.

In [ ]:
tpl = (1, 2, 3, 4, 5)
a, b, c, d, e = tpl
print(a, b, c, d, e)

1 2 3 4 5


21.Convert a list of the first 5 positive integers to a tuple. Print the tuple.

In [ ]:
lst = [1, 2, 3, 4, 5]
tpl = tuple(lst)
print(tpl)

(1, 2, 3, 4, 5)


22.Create a tuple containing 3 tuples, each with 3 elements. Print the tuple of tuples.

In [ ]:
tpl_matrix = ((1,2,3),(4,5,6),(7,8,9))
for tpl in tpl_matrix:
  print(tpl)

(1, 2, 3)
(4, 5, 6)
(7, 8, 9)


23.Create a tuple with the first 5 positive integers. Convert it to a list, append the number 6, and convert it back to a tuple. Print the resulting tuple.

In [ ]:
tpl = tuple(range(1,6))
print('tuple',tpl)
tpl_converted_to_list = list(tpl)
print('tuple converted to list',tpl_converted_to_list)
tpl_converted_to_list.append(6)
print('List with number 6',tpl_converted_to_list)
lst_back_to_tuple = tuple(tpl_converted_to_list)
print('list back to tuple',lst_back_to_tuple)

tuple (1, 2, 3, 4, 5)
tuple converted to list [1, 2, 3, 4, 5]
List with number 6 [1, 2, 3, 4, 5, 6]
list back to tuple (1, 2, 3, 4, 5, 6)


24.Create a tuple with the characters of a string. Join the tuple elements into a single string. Print the string.

In [ ]:
string_tple = ('t','e','s','t','i','n','g')
final_string = ''
for i in string_tple:
  final_string += i
print(final_string)


testing


In [ ]:
string = "hello"
tpl = tuple(string)
joined_string = ''.join(tpl)
print(joined_string)

hello


25.Create a dictionary with tuple keys and integer values. Print the dictionary.

In [ ]:
tpl_dict = {
    (1, 2): 3,
    (4, 5): 6,
    (7, 8): 9
}
print(tpl_dict)

{(1, 2): 3, (4, 5): 6, (7, 8): 9}


26.Create a nested tuple and iterate over the elements, printing each element.

In [ ]:
nested_tpl = ((1,2,3),(4,5,6),(7,8,9))
for i in nested_tpl:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8
9


27.Create a tuple with duplicate elements. Convert it to a set to remove duplicates and print the resulting set.

In [ ]:
tpl = (1, 2, 2, 3, 4, 4, 4, 5)
unique_set = set(tpl)
print(unique_set)

{1, 2, 3, 4, 5}


28.Write functions that take a tuple and return the minimum, maximum, and sum of the elements. Print the results for a sample tuple.

In [ ]:
def min_in_tuple(tpl):
    return min(tpl)

def max_in_tuple(tpl):
    return max(tpl)

def sum_of_tuple(tpl):
    return sum(tpl)

sample_tpl = (1, 2, 3, 4, 5)
print(f"Minimum: {min_in_tuple(sample_tpl)}")
print(f"Maximum: {max_in_tuple(sample_tpl)}")
print(f"Sum: {sum_of_tuple(sample_tpl)}")

29.Set operations


In [ ]:
#create
set_val = set(range(1,11))
print("set",set_val)

#update
set_val.add(11)
set_val.remove(1)
print('updated set',set_val)

set {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
updated set {2, 3, 4, 5, 6, 7, 8, 9, 10, 11}


30. Create two sets: one with the first 5 positive integers and another with the first 5 even integers. Perform and print the results of union, intersection, difference, and symmetric difference operations on these sets.

In [ ]:
set1 = set(range(1, 6))
set2 = set(range(2, 11, 2))
print(f"Union: {set1 | set2}")
print(f"Intersection: {set1 & set2}")
print(f"Difference (set1 - set2): {set1 - set2}")
print(f"Symmetric Difference: {set1 ^ set2}")

31.Create a new set containing the squares of the first 10 positive integers using a set comprehension. Print the new set.

In [ ]:
squares = {x**2 for x in range(1, 11)}
print(squares)

{64, 1, 4, 36, 100, 9, 16, 49, 81, 25}


32.Create two sets: one with the first 5 positive integers and another with the first 3 positive integers. Check if the second set is a subset of the first set and if the first set is a superset of the second set. Print the results.

In [ ]:
set1 = set(range(1, 6))
set2 = set(range(1, 4))
print(f"Is set2 a subset of set1? {set2.issubset(set1)}")
print(f"Is set1 a superset of set2? {set1.issuperset(set2)}")

Is set2 a subset of set1? True
Is set1 a superset of set2? True


33.Create a frozenset with the first 5 positive integers. Print the frozenset.

A frozenset in Python is an immutable version of a standard set. Like a regular set, it is an unordered collection of unique elements, but once created, its contents cannot be modified (no elements can be added, removed, or changed).

In [ ]:
fs = frozenset(range(1, 6))
print(fs)

frozenset({1, 2, 3, 4, 5})


34.Create a set with the first 5 positive integers. Convert it to a list, append the number 6, and convert it back to a set. Print the resulting set.

In [ ]:
set_var = set(range(1,6))
print('set',set_var)
set_converted_to_list = list(set_var)
set_converted_to_list.append(6)
set_var = set(set_converted_to_list)
print('list',set_var)

set {1, 2, 3, 4, 5}
list {1, 2, 3, 4, 5, 6}


35.Create a dictionary with set keys and integer values. Print the dictionary.

In [ ]:
d = {
    frozenset({1, 2}): 3,
    frozenset({3, 4}): 7,
    frozenset({5, 6}): 11
}
print(d)

{frozenset({1, 2}): 3, frozenset({3, 4}): 7, frozenset({5, 6}): 11}


In [ ]:
#36.iterating over set
s = set(range(1, 6))
for elem in s:
    print('elem',elem)

#check if an element is present in the set
print(3 in s)
print(6 in s)

#removing a element
while s:
    s.pop()
    print(s)

elem 1
elem 2
elem 3
elem 4
elem 5
True
False
{2, 3, 4, 5}
{3, 4, 5}
{4, 5}
{5}
set()


37.Create two sets and update the first set with the symmetric difference of the two sets. Print the modified first set.

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
set1.symmetric_difference_update(set2)
print(set1)

{1, 2, 4, 5}


38.Create a dictionary with the first 10 positive integers as keys and their squares as values. Print the dictionary.

In [ ]:
d = {i: i**2 for i in range(1, 11)}
print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


39.Create a dictionary where the keys are the first 5 positive integers and the values are lists containing the first 5 multiples of the key. Print the dictionary.

In [ ]:
multiples = {i:[i*j for j in range(1,6)]for i in range(1,6)}
print(multiples)

{1: [1, 2, 3, 4, 5], 2: [2, 4, 6, 8, 10], 3: [3, 6, 9, 12, 15], 4: [4, 8, 12, 16, 20], 5: [5, 10, 15, 20, 25]}


40.Create a dictionary where the keys are the first 5 positive integers and the values are tuples containing the key and its square. Print the dictionary.

In [ ]:
squares = {i:(i,i**2) for i in range(1,6)}
print(squares)
list_of_tuples = list(squares.items())
print(list_of_tuples)

{1: (1, 1), 2: (2, 4), 3: (3, 9), 4: (4, 16), 5: (5, 25)}
[(1, (1, 1)), (2, (2, 4)), (3, (3, 9)), (4, (4, 16)), (5, (5, 25))]


41.Create a new dictionary containing only the key-value pairs where the key is even.

In [ ]:
dictionary = {i : i**2 for i in range(1,20)}
print(dictionary)
even_dict = {k:v for k,v in dictionary.items() if k%2 == 0}
print(even_dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361}
{2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196, 16: 256, 18: 324}


43.Create a dictionary with the first 5 positive integers as keys and their squares as values. Create a new dictionary with keys and values swapped. Print the new dictionary.

In [ ]:
positive_dict ={ i: i**2 for i in range(1,6)}
print(positive_dict)
swapped = {v:k for k,v in positive_dict.items()}
print(swapped)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
{1: 1, 4: 2, 9: 3, 16: 4, 25: 5}


44. In Python, a defaultdict is a specialized dictionary class from the collections module that automatically assigns a default value to keys that do not yet exist. This allows you to perform operations like appending to a list or incrementing a counter without first checking if the key is present, effectively avoiding the common KeyError

In [ ]:
from collections import defaultdict

# int() returns 0 by default
counts = defaultdict(int)
print('counts',counts['apple'])
words = ["apple", "banana", "apple", "orange", "banana", "apple"]

for word in words:
    # If word isn't a key, it's created with a value of 0, then incremented
    counts[word] += 1

print(dict(counts))

counts 0
{'apple': 3, 'banana': 2, 'orange': 1}


1. int sets 0 as default value
2. Set sets {}
3. List sets []
4. lambda sets a user defined value as a default value
    user_settings = defaultdict(lambda: "Enabled")

45. Write a function that takes a string and returns a dictionary with the count of each character in the string. Print the dictionary.

In [ ]:
def count_chars(s):
    count_dict = {}
    for char in s:
        count_dict[char] = count_dict.get(char, 0) + 1
    return count_dict

string = "hello world"
print(count_chars(string))

46.You are given a list of integers. Write a Python program that checks if all elements in the list are unique. If all elements are unique, return True; otherwise, return False

In [ ]:
def are_elements_unique(lst):
    return len(lst) == len(set(lst))
print(are_elements_unique([1, 2, 3, 4]))   # True
print(are_elements_unique([1, 2, 2, 3]))   # False

True
False


47.Reversing the list

In [ ]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]

def reverese_the_list(lst):
  reversed_list = []
  for i in range(len(lst) - 1, -1, -1):
    reversed_list.append(lst[i])
  return reversed_list

print(lst1[::-1])
lst2.reverse()
print(lst2)
print(reverese_the_list(lst3))

[5, 4, 3, 2, 1]
[10, 9, 8, 7, 6]
[15, 14, 13, 12, 11]


48.You are given a list of integers and an integer k. Write a Python function to rotate the list to the right by k positions without using slicing. A rotation shifts elements from the end of the list to the front

In [ ]:
def rotate_list(lst, k):
    n = len(lst)
    if n == 0:
        return lst

    k = k % n   # Handle k > n

    for _ in range(k):
        last = lst.pop()     # Remove last element
        lst.insert(0, last)  # Insert at beginning

    return lst
print(rotate_list([1, 2, 3, 4, 5], 2))

[4, 5, 1, 2, 3]


49.Design a Python function named merge_lists_to_dictionary to merge two lists into a dictionary where elements from the first list act as keys and elements from the second list act as values.

In [ ]:
def merge_lists_to_dictionary(keys, values):
    # Boundary Condition to check for equal length of keys and values.
    # Last point in problem solving framework :)
    if(len(keys) != len(values)):
        return False
    # Create an empty dictionary to store the result
    result = {}

    # Use a loop to iterate through both lists
    for i in range(len(keys)):
        # Add each key-value pair to the dictionary
        result[keys[i]] = values[i]

    return result


50. Merge dictionaries

In [ ]:
d1 = {"a": 1, "b": 2}
d2 = {"c": 3, "d": 4}
d3 = {"e": 5, "f": 6}
merged = {**d1, **d2, **d3}
print(merged)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


51.Design a Python function named count_word_frequency to count the frequency of words in a sentence and store the counts in a dictionary.

In [ ]:
def count_word_frequency(sentence):
    # Initialize an empty dictionary to store word frequencies
    word_count = {}

    # Split the sentence into words using space as the delimiter
    words = sentence.split()

    # Iterate through each word in the list of words
    for word in words:
        # If the word is already in the dictionary, increment its count
        if word in word_count:
            word_count[word] += 1
        # If the word is not in the dictionary, add it with a count of 1
        else:
            word_count[word] = 1

    return word_count

sts = "hello world hello"
count_word_frequency(sts)

{'hello': 2, 'world': 1}

52. Tuple is palindrome

In [ ]:
def is_palindromic_tuple(tup):
    print(tup == tup[::-1])
is_palindromic_tuple((1, 2, 3, 2, 1))
is_palindromic_tuple((1, 3, 2, 1))
is_palindromic_tuple(('a',))

True
False
True


53.Define a recursive function to calculate the nth Fibonacci number using memoization. Test the function with different inputs.

In [ ]:
def fibonacci(n, memo={}):
    if n in memo:
        return memo[n]
    if n <= 1:
        return n
    memo[n] = fibonacci(n - 1, memo) + fibonacci(n - 2, memo)
    return memo[n]

# Test
print(fibonacci(10))  # 55
print(fibonacci(15))  # 610

55
610


54.Define a function that takes a variable number of keyword arguments and returns a dictionary containing only those key-value pairs where the value is an integer. Test the function with different inputs.

In [ ]:
def filter_integers(**kwargs):
    return {k: v for k, v in kwargs.items() if isinstance(v, int)}

# Test
print(filter_integers(a=1, b='two', c=3, d=4.5))  # {'a': 1, 'c': 3}
print(filter_integers(x=10, y='yes', z=20))  # {'x': 10, 'z': 20}

{'a': 1, 'c': 3}
{'x': 10, 'z': 20}


55.Define a function that takes another function as a callback and a list of integers. The function should apply the callback to each integer in the list and return a new list with the results. Test with different callback functions.

In [ ]:
def apply_callback(callback, lst):
    return [callback(x) for x in lst]

# Test
print(apply_callback(lambda x: x**2, [1, 2, 3, 4]))  # [1, 4, 9, 16]
print(apply_callback(lambda x: x+1, [1, 2, 3, 4]))  # [2, 3, 4, 5]

[1, 4, 9, 16]
[2, 3, 4, 5]


56.Define a function that returns another function. The returned function should take an integer and return its square. Test the returned function with different inputs.

In [ ]:
def outer_function():
    def inner_function(x):
        return x ** 2
    return inner_function

# Test
square = outer_function()
print(square(2))  # 4
print(square(5))  # 25

4
25


57.Define a function that calculates the time taken to execute another function. Apply this decorator to a function that performs a complex calculation. Test the decorated function with different inputs.

In [ ]:
import time

def timer_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Function {func.__name__} took {end_time - start_time} seconds to execute.")
        return result
    return wrapper

@timer_decorator
def complex_calculation(n):
    return sum(x**2 for x in range(n))

# Test
print(complex_calculation(10000))

Function complex_calculation took 0.000926971435546875 seconds to execute.
333283335000


58.Define a higher-order function that takes two functions, a filter function and a map function, along with a list of integers. The higher-order function should first filter the integers using the filter function and then apply the map function to the filtered integers. Test with different filter and map functions.

In [ ]:
def filter_and_map(filter_func, map_func, lst):
    return [map_func(x) for x in lst if filter_func(x)]

# Test
print(filter_and_map(lambda x: x % 2 == 0, lambda x: x ** 2, [1, 2, 3, 4, 5]))  # [4, 16]
print(filter_and_map(lambda x: x > 2, lambda x: x + 1, [1, 2, 3, 4, 5]))  # [4, 5, 6]

[4, 16]
[4, 5, 6]


HOF is a function that follow either one of the below conditions or both of them
1. Take more than one function as argument
2. Returns an argument

59.Define a function that composes two functions, f and g, such that the result is f(g(x)). Test with different functions f and g.

In [ ]:
def compose(f, g):
    return lambda x: f(g(x))

# Test
f = lambda x: x + 1
g = lambda x: x * 2
h = compose(f, g)
print(h(3))  # 7
print(h(5))  # 11

7
11


60.Use the functools.partial function to create a new function that multiplies its input by 2. Test the new function with different inputs.

In [ ]:
from functools import partial

multiply_by_2 = partial(lambda x, y: x * y, 2)

# Test
print(multiply_by_2(3))  # 6
print(multiply_by_2(5))  # 10

6
10


61.Define a function that takes a list of integers and returns their average. The function should handle any errors that occur (e.g., empty list) and return None in such cases. Test with different inputs.

In [ ]:
def average(lst):
    try:
        return sum(lst) / len(lst)
    except ZeroDivisionError:
        return None

# Test
print(average([1, 2, 3, 4, 5]))  # 3.0
print(average([]))  # None

3.0
None


62.Define a function that generates an infinite sequence of Fibonacci numbers. Test by printing the first 10 numbers in the sequence.

In [ ]:
def fibonacci_generator():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b

# Test
fib_gen = fibonacci_generator()
for _ in range(10):
    print(next(fib_gen))

0
1
1
2
3
5
8
13
21
34


63.Define a curried function that takes three arguments, one at a time, and returns their product. Test the function by providing arguments one at a time.

In [ ]:
def curry_product(x):
    def inner1(y):
        def inner2(z):
            return x * y * z
        return inner2
    return inner1

# Test
print(curry_product(2)(3)(4))  # 24
print(curry_product(1)(5)(6))  # 30

24
30


64.Define a function that uses a context manager to write a list of integers to a file. The function should handle any errors that occur during file operations. Test with different lists.

In [ ]:
def write_to_file(lst, filename):
    try:
        with open(filename, 'w') as f:
            for num in lst:
                f.write(f"{num}\n")
    except IOError as e:
        print(f"An error occurred: {e}")

# Test
write_to_file([1, 2, 3, 4, 5], 'output.txt')

65.Define a function that takes a list of mixed data types (integers, strings, and floats) and returns three lists: one containing all the integers, one containing all the strings, and one containing all the floats. Test with different inputs.

In [ ]:
def separate_types(lst):
    ints, strs, floats = [], [], []
    for item in lst:
        if isinstance(item, int):
            ints.append(item)
        elif isinstance(item, str):
            strs.append(item)
        elif isinstance(item, float):
            floats.append(item)
    return ints, strs, floats

# Test
print(separate_types([1, 'a', 2.5, 3, 'b', 4.0, 'c']))  # ([1, 3], ['a', 'b', 'c'], [2.5, 4.0])

66.Define a function that maintains state between calls using a mutable default argument. The function should keep track of how many times it has been called. Test by calling the function multiple times.

In [ ]:
def call_counter(counter={'count': 0}):
    counter['count'] += 1
    return counter['count']

# Test
print(call_counter())  # 1
print(call_counter())  # 2
print(call_counter())  # 3

67. Check if a string has a digit


In [ ]:
# in python we cannot call a function before defining it
def checkDigitInString(password):
  if not any(char.isdigit() for char in password):
    print(password,'Doesnt contain any digit')

checkDigitInString('Test123')
checkDigitInString('Test')

Test Doesnt contain any digit


68. String is a palindrome

In [ ]:
def stringPalindrome(str1):
    if str1 == str1[::-1]:
      print(str1, 'is a palindrome')
    else:
      print(str1, 'is not a palindrome')
stringPalindrome('abcba')
stringPalindrome('Test')

abcba is a palindrome
Test is not a palindrome


69.Write a function that reads the contents of a file named `document.txt` and returns the number of words in the file.

In [ ]:
def count_words(filename):
    with open(filename, 'r') as file:
        text = file.read()
        words = text.split()
        return len(words)

# Test
# print(count_words('document.txt'))

70.Write a function that finds and replaces all occurrences of a given word in a file named `data.txt` with another word.

In [ ]:
def find_and_replace(filename, old_word, new_word):
    with open(filename, 'r') as file:
        text = file.read()
    new_text = text.replace(old_word, new_word)
    with open(filename, 'w') as file:
        file.write(new_text)


71.Write a function that reads the contents of a file named `reverse.txt` and prints each line in reverse order.

In [ ]:
def read_reverse(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
    for line in reversed(lines):
        print(line.strip())

72.Write a function that reads the contents of a file named `stats.txt` and returns the number of lines, words, and characters in the file.

In [ ]:
def count_lwc(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        words = sum(len(line.split()) for line in lines)
        characters = sum(len(line) for line in lines)
    return len(lines), words, characters

73.Write a function that merges the contents of multiple files into a single file named `merged.txt`.

In [ ]:
def merge_files(file_list, output_file):
    with open(output_file, 'w') as outfile:
        for fname in file_list:
            with open(fname, 'r') as infile:
                outfile.write(infile.read() + '\n')



74.Write a function that splits a large file named `large.txt` into smaller files of 100 lines each.

In [ ]:
def split_file(filename, lines_per_file):
    with open(filename, 'r') as file:
        lines = file.readlines()
    for i in range(0, len(lines), lines_per_file):
        with open(f'{filename}_part{i//lines_per_file + 1}.txt', 'w') as part_file:
            part_file.writelines(lines[i:i + lines_per_file])

75.Write a function that creates a log file named `activity.log` and writes log messages with timestamps.

In [ ]:
import datetime

def log_message(message, filename='activity.log'):
    timestamp = datetime.datetime.now().isoformat()
    with open(filename, 'a') as file:
        file.write(f'[{timestamp}] {message}\n')

# Test
# log_message('This is a log message.')

76.Write a function that reads a binary file named `image.bin` and writes its contents to another binary file named `copy_image.bin`.

In [ ]:
def copy_binary_file(source, destination):
    with open(source, 'rb') as src:
        with open(destination, 'wb') as dest:
            dest.write(src.read())

# Test
# copy_binary_file('image.bin', 'copy_image.bin')

77.Write a function that reads a CSV file named `data.csv` and prints its contents as a list of dictionaries.

In [ ]:
import csv

def read_csv_as_dicts(filename):
    with open(filename, 'r') as file:
        reader = csv.DictReader(file)
        return list(reader)

78.Write a function that reads a JSON file named `data.json` and prints its contents as a Python dictionary.

In [ ]:
import json

def read_json(filename):
    with open(filename, 'r') as file:
        data = json.load(file)
        return data

79.Write a function that attempts to read a file named `protected.txt` and handles any permission errors gracefully by printing an error message.

In [ ]:
def read_protected_file(filename):
    try:
        with open(filename, 'r') as file:
            print(file.read())
    except PermissionError as e:
        print(f"Permission error: {e}")

78.Write code that attempts to import a non-existent module and gracefully handles the import error by printing an error message.

In [ ]:
try:
    import non_existent_module
except ImportError as e:
    print(f"Error importing module: {e}")

79.Write a function that takes two integers as input and returns their division. Use try, except, and finally blocks to handle division by zero and print an appropriate message.

In [ ]:
def divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError as e:
        print(f"Error: {e}")
        result = None
    finally:
        print("Execution complete.")
    return result

# Test
# print(divide(10, 2))  # 5.0
# print(divide(10, 0))  # None

80.Write a function that reads the contents of a file named `data.txt`. Use try, except, and finally blocks to handle file not found errors and ensure the file is properly closed.

In [ ]:
def read_file(filename):
    try:
        file = open(filename, 'r')
        content = file.read()
        return content
    except FileNotFoundError as e:
        print(f"Error: {e}")
    finally:
        try:
            file.close()
        except NameError:
            pass

# Test
# print(read_file('data.txt'))

81.Write a function that takes a list of integers and returns their sum. Use try, except, and finally blocks to handle TypeError if a non-integer value is encountered and print an appropriate message.

In [ ]:
def sum_list(lst):
    total = 0
    try:
        for item in lst:
            total += item
    except TypeError as e:
        print(f"Error: {e}")
        total = None
    finally:
        print("Execution complete.")
    return total

# Test
# print(sum_list([1, 2, 3, 'a']))  # None
# print(sum_list([1, 2, 3, 4]))  # 10

82.Write a function that prompts the user to enter an integer. Use try, except, and finally blocks to handle ValueError if the user enters a non-integer value and print an appropriate message.

In [ ]:
def get_integer():
    try:
        value = int(input("Enter an integer: "))
    except ValueError as e:
        print(f"Error: {e}")
        value = None
    finally:
        print("Execution complete.")
    return value

# Test
# print(get_integer())

83.Write a function that takes a dictionary and a key as input and returns the value associated with the key. Use try, except, and finally blocks to handle KeyError if the key is not found in the dictionary and print an appropriate message.

In [ ]:
def get_dict_value(d, key):
    try:
        value = d[key]
    except KeyError as e:
        print(f"Error: {e}")
        value = None
    finally:
        print("Execution complete.")
    return value

# Test
# d = {'a': 1, 'b': 2, 'c': 3}
# print(get_dict_value(d, 'b'))  # 2
# print(get_dict_value(d, 'x'))  # None

84.Write a function that performs nested exception handling. It should first attempt to convert a string to an integer, and then attempt to divide by that integer. Use nested try, except, and finally blocks to handle ValueError and ZeroDivisionError and print appropriate messages.

In [ ]:
def nested_exception_handling(s):
    try:
        try:
            num = int(s)
        except ValueError as e:
            print(f"Conversion error: {e}")
            num = None
        finally:
            print("Conversion attempt complete.")
        if num is not None:
            try:
                result = 10 / num
            except ZeroDivisionError as e:
                print(f"Division error: {e}")
                result = None
            finally:
                print("Division attempt complete.")
            return result
    finally:
        print("Overall execution complete.")

# Test
# print(nested_exception_handling('0'))  # None
# print(nested_exception_handling('a'))  # None
# print(nested_exception_handling('2'))  # 5.0

85.Write a function that takes a list and an index as input and returns the element at the given index. Use try, except, and finally blocks to handle IndexError if the index is out of range and print an appropriate message.

In [ ]:
def get_list_element(lst, index):
    try:
        element = lst[index]
    except IndexError as e:
        print(f"Error: {e}")
        element = None
    finally:
        print("Execution complete.")
    return element

# Test
# lst = [1, 2, 3, 4, 5]
# print(get_list_element(lst, 2))  # 3
# print(get_list_element(lst, 10))  # None

86.Write a function that attempts to open a URL and read its contents. Use try, except, and finally blocks to handle network-related errors and print an appropriate message.

In [ ]:
import requests

def read_url(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        return response.text
    except requests.RequestException as e:
        print(f"Network error: {e}")
        return None
    finally:
        print("Execution complete.")

# Test
# print(read_url('https://jsonplaceholder.typicode.com/posts/1'))
# print(read_url('https://nonexistent.url'))

87.Write a function that attempts to parse a JSON string. Use try, except, and finally blocks to handle JSONDecodeError if the string is not a valid JSON and print an appropriate message.

In [ ]:
import json

def parse_json(json_string):
    try:
        data = json.loads(json_string)
        return data
    except json.JSONDecodeError as e:
        print(f"JSON error: {e}")
        return None
    finally:
        print("Execution complete.")

# Test
# print(parse_json('{"name": "John", "age": 30}'))  # {'name': 'John', 'age': 30}
# print(parse_json('Invalid JSON'))  # None

88.Define a custom exception named `NegativeNumberError`. Write a function that raises this exception if a negative number is encountered in a list. Use try, except, and finally blocks to handle the custom exception and print an appropriate message.

In [ ]:
class NegativeNumberError(Exception):
    pass

def check_for_negatives(lst):
    try:
        for num in lst:
            if num < 0:
                raise NegativeNumberError(f"Negative number found: {num}")
    except NegativeNumberError as e:
        print(f"Error: {e}")
    finally:
        print("Execution complete.")

# Test
# check_for_negatives([1, -2, 3, 4])  # Error: Negative number found: -2
# check_for_negatives([1, 2, 3, 4])  # Execution complete.

89.Write a function that calls another function which may raise an exception. Use try, except, and finally blocks to handle the exception and print an appropriate message.

In [ ]:
def risky_function():
    raise ValueError("An error occurred in risky_function.")

def safe_function():
    try:
        risky_function()
    except ValueError as e:
        print(f"Error: {e}")
    finally:
        print("Execution complete.")

# Test
# safe_function()  # Error: An error occurred in risky_function.

90.Define a class with a method that performs a division operation. Use try, except, and finally blocks within the method to handle division by zero and print an appropriate message.

In [ ]:
class Calculator:
    def divide(self, a, b):
        try:
            result = a / b
        except ZeroDivisionError as e:
            print(f"Error: {e}")
            result = None
        finally:
            print("Execution complete.")
        return result

# Test
# calc = Calculator()
# print(calc.divide(10, 2))  # 5.0
# print(calc.divide(10, 0))  # None

91.Write a function that takes a list of strings and converts them to integers. Use try, except, and finally blocks to handle ValueError if a string cannot be converted and print an appropriate message.

In [ ]:
def convert_to_integers(lst):
    integers = []
    try:
        for item in lst:
            integers.append(int(item))
    except ValueError as e:
        print(f"Error: {e}")
        integers = None
    finally:
        print("Execution complete.")
    return integers

# Test
# print(convert_to_integers(['1', '2', 'three', '4']))  # None
# print(convert_to_integers(['1', '2', '3', '4']))  # [1, 2, 3, 4]

92.Write a function that uses a list comprehension to convert a list of strings to integers. Use try, except, and finally blocks within the list comprehension to handle ValueError and print an appropriate message.

In [ ]:
def convert_with_comprehension(lst):
    try:
        integers = [int(item) for item in lst]
    except ValueError as e:
        print(f"Error: {e}")
        integers = None
    finally:
        print("Execution complete.")
    return integers

# Test
# print(convert_with_comprehension(['1', '2', 'three', '4']))  # None
# print(convert_with_comprehension(['1', '2', '3', '4']))  # [1, 2, 3, 4]

93.Write a function that attempts to write a list of strings to a file. Use try, except, and finally blocks to handle IOError and ensure the file is properly closed.

In [ ]:
def write_strings_to_file(strings, filename):
    try:
        file = open(filename, 'w')
        for string in strings:
            file.write(string + '\n')
    except IOError as e:
        print(f"Error: {e}")
    finally:
        try:
            file.close()
        except NameError:
            pass

# Test
# write_strings_to_file(['Hello', 'World'], 'output.txt')

94
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Replace the diagonal elements with 0
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
[[ 9  7 20 18  2]
 [10 11 12  5 15]
 [17  1 17 12  7]
 [15  6  3 13  9]
 [14  1  1  3  7]]
Modified array:
[[ 9  7  1 18  2]
 [10 11  1  5 15]
 [17  1  1 12  7]
 [15  6  1 13  9]
 [14  1  1  3  7]]
Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


95
 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

# Extract the sub-array
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]
Original array:
[[18 11 15 12  7]
 [ 7 14  5 12 17]
 [ 5  1 12 11 19]
 [13  7  1  5 11]
 [ 8  5  5  8 12]]
Border elements:
[18 11 15 12  7  8  5  5  8 12  7  5 13 17 19 11]


96.Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [5]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


97.Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting

Broadcasting in Python usually refers to NumPy broadcasting, which allows arrays of different shapes to perform arithmetic operations together without manually resizing them. It automatically expands the smaller array to match the larger array

In [6]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[1 7 2]
 [3 3 6]
 [1 2 4]]
1D array:
[10 10  4]
Resulting array:
[[11 17  6]
 [13 13 10]
 [11 12  8]]
